name: BWF Calendar Scraper Weekly

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 google-api-python-client python-dateutil

      - name: Create credentials.json
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > credentials.json

      - name: Set environment variables
        run: echo "GOOGLE_CALENDAR_ID=${{ secrets.GOOGLE_CALENDAR_ID }}" >> $GITHUB_ENV

      - name: Run BWF calendar bot
        run: python bwf-calendar-bot.py
