name: BWF Calendar Scraper

# Run on the 1st day of every month at 9:00 UTC and manually via workflow_dispatch
on:
  schedule:
    - cron: "0 9 1 * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install playwright
          playwright install

      # 4. Recreate credentials.json from Base64 secret
      - name: Create credentials.json
        run: printf '%s' "${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > credentials.json

      # 5. Set Calendar ID as environment variable
      - name: Set Calendar ID
        run: echo "GOOGLE_CALENDAR_ID=${{ secrets.GOOGLE_CALENDAR_ID }}" >> $GITHUB_ENV

      # 6. Run scraper
      - name: Run BWF scraper
        run: python bwf-calendar-bot.py
